// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.AutoRestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApproveChallengeRequest
    {
        /// <summary>
        /// Initializes a new instance of the ApproveChallengeRequest class.
        /// </summary>
        public ApproveChallengeRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApproveChallengeRequest class.
        /// </summary>
        /// <param name="recoveryId">An id of the recovery</param>
        /// <param name="challenge">A challenge to approve. Possible values
        /// include: 'Unknown', 'Sms', 'Email', 'Selfie', 'Words', 'Device',
        /// 'Pin', 'Undefined'</param>
        /// <param name="agentId">An agent id</param>
        /// <param name="checkResult">Resolution. Possible values include:
        /// 'Unknown', 'Approved', 'Rejected'</param>
        public ApproveChallengeRequest(string recoveryId, Challenge challenge, string agentId, CheckResult checkResult)
        {
            RecoveryId = recoveryId;
            Challenge = challenge;
            AgentId = agentId;
            CheckResult = checkResult;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an id of the recovery
        /// </summary>
        [JsonProperty(PropertyName = "recoveryId")]
        public string RecoveryId { get; set; }

        /// <summary>
        /// Gets or sets a challenge to approve. Possible values include:
        /// 'Unknown', 'Sms', 'Email', 'Selfie', 'Words', 'Device', 'Pin',
        /// 'Undefined'
        /// </summary>
        [JsonProperty(PropertyName = "challenge")]
        public Challenge Challenge { get; set; }

        /// <summary>
        /// Gets or sets an agent id
        /// </summary>
        [JsonProperty(PropertyName = "agentId")]
        public string AgentId { get; set; }

        /// <summary>
        /// Gets or sets resolution. Possible values include: 'Unknown',
        /// 'Approved', 'Rejected'
        /// </summary>
        [JsonProperty(PropertyName = "checkResult")]
        public CheckResult CheckResult { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RecoveryId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RecoveryId");
            }
            if (AgentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AgentId");
            }
            if (RecoveryId != null)
            {
                if (RecoveryId.Length < 8)
                {
                    throw new ValidationException(ValidationRules.MinLength, "RecoveryId", 8);
                }
            }
        }
    }
}
