// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.AutoRestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CheckResult.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CheckResult
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Approved")]
        Approved,
        [EnumMember(Value = "Rejected")]
        Rejected
    }
    internal static class CheckResultEnumExtension
    {
        internal static string ToSerializedValue(this CheckResult? value)
        {
            return value == null ? null : ((CheckResult)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CheckResult value)
        {
            switch( value )
            {
                case CheckResult.Unknown:
                    return "Unknown";
                case CheckResult.Approved:
                    return "Approved";
                case CheckResult.Rejected:
                    return "Rejected";
            }
            return null;
        }

        internal static CheckResult? ParseCheckResult(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return CheckResult.Unknown;
                case "Approved":
                    return CheckResult.Approved;
                case "Rejected":
                    return CheckResult.Rejected;
            }
            return null;
        }
    }
}
