// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.AutoRestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NewRecoveryRequest
    {
        /// <summary>
        /// Initializes a new instance of the NewRecoveryRequest class.
        /// </summary>
        public NewRecoveryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NewRecoveryRequest class.
        /// </summary>
        /// <param name="clientId">An id of Client</param>
        /// <param name="ip">Client's ip</param>
        /// <param name="userAgent">Client's user agent</param>
        public NewRecoveryRequest(string clientId, string ip, string userAgent)
        {
            ClientId = clientId;
            Ip = ip;
            UserAgent = userAgent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an id of Client
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or sets client's ip
        /// </summary>
        [JsonProperty(PropertyName = "ip")]
        public string Ip { get; set; }

        /// <summary>
        /// Gets or sets client's user agent
        /// </summary>
        [JsonProperty(PropertyName = "userAgent")]
        public string UserAgent { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ClientId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ClientId");
            }
            if (Ip == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ip");
            }
            if (UserAgent == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserAgent");
            }
            if (ClientId != null)
            {
                if (ClientId.Length < 8)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ClientId", 8);
                }
            }
            if (UserAgent != null)
            {
                if (UserAgent.Length > 128)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "UserAgent", 128);
                }
            }
        }
    }
}
