// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.AutoRestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResolutionRequest
    {
        /// <summary>
        /// Initializes a new instance of the ResolutionRequest class.
        /// </summary>
        public ResolutionRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResolutionRequest class.
        /// </summary>
        /// <param name="recoveryId">An id of the recovery</param>
        /// <param name="resolution">A resolution from support. Possible values
        /// include: 'Unknown', 'Suspend', 'Interview', 'Freeze',
        /// 'Allow'</param>
        /// <param name="agentId">Client's ip</param>
        /// <param name="comment">Client's user agent</param>
        public ResolutionRequest(string recoveryId, Resolution resolution, string agentId, string comment)
        {
            RecoveryId = recoveryId;
            Resolution = resolution;
            AgentId = agentId;
            Comment = comment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets an id of the recovery
        /// </summary>
        [JsonProperty(PropertyName = "recoveryId")]
        public string RecoveryId { get; set; }

        /// <summary>
        /// Gets or sets a resolution from support. Possible values include:
        /// 'Unknown', 'Suspend', 'Interview', 'Freeze', 'Allow'
        /// </summary>
        [JsonProperty(PropertyName = "resolution")]
        public Resolution Resolution { get; set; }

        /// <summary>
        /// Gets or sets client's ip
        /// </summary>
        [JsonProperty(PropertyName = "agentId")]
        public string AgentId { get; set; }

        /// <summary>
        /// Gets or sets client's user agent
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RecoveryId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RecoveryId");
            }
            if (AgentId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AgentId");
            }
            if (Comment == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Comment");
            }
            if (RecoveryId != null)
            {
                if (RecoveryId.Length < 8)
                {
                    throw new ValidationException(ValidationRules.MinLength, "RecoveryId", 8);
                }
            }
            if (Comment != null)
            {
                if (Comment.Length > 256)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "Comment", 256);
                }
            }
        }
    }
}
