// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.AutoRestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for Trigger.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Trigger
    {
        [EnumMember(Value = "RecoveryRequest")]
        RecoveryRequest,
        [EnumMember(Value = "SecretPhrasesComplete")]
        SecretPhrasesComplete,
        [EnumMember(Value = "SecretPhrasesSkip")]
        SecretPhrasesSkip,
        [EnumMember(Value = "SecretPhrasesVerificationFail")]
        SecretPhrasesVerificationFail,
        [EnumMember(Value = "DeviceVerificationComplete")]
        DeviceVerificationComplete,
        [EnumMember(Value = "DeviceVerificationSkip")]
        DeviceVerificationSkip,
        [EnumMember(Value = "DeviceVerificationFail")]
        DeviceVerificationFail,
        [EnumMember(Value = "SmsVerificationComplete")]
        SmsVerificationComplete,
        [EnumMember(Value = "SmsVerificationRestart")]
        SmsVerificationRestart,
        [EnumMember(Value = "SmsVerificationFail")]
        SmsVerificationFail,
        [EnumMember(Value = "SmsVerificationSkip")]
        SmsVerificationSkip,
        [EnumMember(Value = "EmailVerificationComplete")]
        EmailVerificationComplete,
        [EnumMember(Value = "EmailVerificationRestart")]
        EmailVerificationRestart,
        [EnumMember(Value = "EmailVerificationFail")]
        EmailVerificationFail,
        [EnumMember(Value = "EmailVerificationSkip")]
        EmailVerificationSkip,
        [EnumMember(Value = "PinComplete")]
        PinComplete,
        [EnumMember(Value = "PinSkip")]
        PinSkip,
        [EnumMember(Value = "PinFail")]
        PinFail,
        [EnumMember(Value = "SelfieVerificationRequest")]
        SelfieVerificationRequest,
        [EnumMember(Value = "SelfieVerificationComplete")]
        SelfieVerificationComplete,
        [EnumMember(Value = "SelfieVerificationSkip")]
        SelfieVerificationSkip,
        [EnumMember(Value = "SelfieVerificationFail")]
        SelfieVerificationFail,
        [EnumMember(Value = "JumpToSuspended")]
        JumpToSuspended,
        [EnumMember(Value = "JumpToCallSupport")]
        JumpToCallSupport,
        [EnumMember(Value = "JumpToFrozen")]
        JumpToFrozen,
        [EnumMember(Value = "JumpToAllowed")]
        JumpToAllowed,
        [EnumMember(Value = "JumpToForbidden")]
        JumpToForbidden,
        [EnumMember(Value = "UpdatePassword")]
        UpdatePassword,
        [EnumMember(Value = "TryUnfreeze")]
        TryUnfreeze
    }
    internal static class TriggerEnumExtension
    {
        internal static string ToSerializedValue(this Trigger? value)
        {
            return value == null ? null : ((Trigger)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this Trigger value)
        {
            switch( value )
            {
                case Trigger.RecoveryRequest:
                    return "RecoveryRequest";
                case Trigger.SecretPhrasesComplete:
                    return "SecretPhrasesComplete";
                case Trigger.SecretPhrasesSkip:
                    return "SecretPhrasesSkip";
                case Trigger.SecretPhrasesVerificationFail:
                    return "SecretPhrasesVerificationFail";
                case Trigger.DeviceVerificationComplete:
                    return "DeviceVerificationComplete";
                case Trigger.DeviceVerificationSkip:
                    return "DeviceVerificationSkip";
                case Trigger.DeviceVerificationFail:
                    return "DeviceVerificationFail";
                case Trigger.SmsVerificationComplete:
                    return "SmsVerificationComplete";
                case Trigger.SmsVerificationRestart:
                    return "SmsVerificationRestart";
                case Trigger.SmsVerificationFail:
                    return "SmsVerificationFail";
                case Trigger.SmsVerificationSkip:
                    return "SmsVerificationSkip";
                case Trigger.EmailVerificationComplete:
                    return "EmailVerificationComplete";
                case Trigger.EmailVerificationRestart:
                    return "EmailVerificationRestart";
                case Trigger.EmailVerificationFail:
                    return "EmailVerificationFail";
                case Trigger.EmailVerificationSkip:
                    return "EmailVerificationSkip";
                case Trigger.PinComplete:
                    return "PinComplete";
                case Trigger.PinSkip:
                    return "PinSkip";
                case Trigger.PinFail:
                    return "PinFail";
                case Trigger.SelfieVerificationRequest:
                    return "SelfieVerificationRequest";
                case Trigger.SelfieVerificationComplete:
                    return "SelfieVerificationComplete";
                case Trigger.SelfieVerificationSkip:
                    return "SelfieVerificationSkip";
                case Trigger.SelfieVerificationFail:
                    return "SelfieVerificationFail";
                case Trigger.JumpToSuspended:
                    return "JumpToSuspended";
                case Trigger.JumpToCallSupport:
                    return "JumpToCallSupport";
                case Trigger.JumpToFrozen:
                    return "JumpToFrozen";
                case Trigger.JumpToAllowed:
                    return "JumpToAllowed";
                case Trigger.JumpToForbidden:
                    return "JumpToForbidden";
                case Trigger.UpdatePassword:
                    return "UpdatePassword";
                case Trigger.TryUnfreeze:
                    return "TryUnfreeze";
            }
            return null;
        }

        internal static Trigger? ParseTrigger(this string value)
        {
            switch( value )
            {
                case "RecoveryRequest":
                    return Trigger.RecoveryRequest;
                case "SecretPhrasesComplete":
                    return Trigger.SecretPhrasesComplete;
                case "SecretPhrasesSkip":
                    return Trigger.SecretPhrasesSkip;
                case "SecretPhrasesVerificationFail":
                    return Trigger.SecretPhrasesVerificationFail;
                case "DeviceVerificationComplete":
                    return Trigger.DeviceVerificationComplete;
                case "DeviceVerificationSkip":
                    return Trigger.DeviceVerificationSkip;
                case "DeviceVerificationFail":
                    return Trigger.DeviceVerificationFail;
                case "SmsVerificationComplete":
                    return Trigger.SmsVerificationComplete;
                case "SmsVerificationRestart":
                    return Trigger.SmsVerificationRestart;
                case "SmsVerificationFail":
                    return Trigger.SmsVerificationFail;
                case "SmsVerificationSkip":
                    return Trigger.SmsVerificationSkip;
                case "EmailVerificationComplete":
                    return Trigger.EmailVerificationComplete;
                case "EmailVerificationRestart":
                    return Trigger.EmailVerificationRestart;
                case "EmailVerificationFail":
                    return Trigger.EmailVerificationFail;
                case "EmailVerificationSkip":
                    return Trigger.EmailVerificationSkip;
                case "PinComplete":
                    return Trigger.PinComplete;
                case "PinSkip":
                    return Trigger.PinSkip;
                case "PinFail":
                    return Trigger.PinFail;
                case "SelfieVerificationRequest":
                    return Trigger.SelfieVerificationRequest;
                case "SelfieVerificationComplete":
                    return Trigger.SelfieVerificationComplete;
                case "SelfieVerificationSkip":
                    return Trigger.SelfieVerificationSkip;
                case "SelfieVerificationFail":
                    return Trigger.SelfieVerificationFail;
                case "JumpToSuspended":
                    return Trigger.JumpToSuspended;
                case "JumpToCallSupport":
                    return Trigger.JumpToCallSupport;
                case "JumpToFrozen":
                    return Trigger.JumpToFrozen;
                case "JumpToAllowed":
                    return Trigger.JumpToAllowed;
                case "JumpToForbidden":
                    return Trigger.JumpToForbidden;
                case "UpdatePassword":
                    return Trigger.UpdatePassword;
                case "TryUnfreeze":
                    return Trigger.TryUnfreeze;
            }
            return null;
        }
    }
}
