// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ApproveChallengeRequest
    {
        /// <summary>
        /// Initializes a new instance of the ApproveChallengeRequest class.
        /// </summary>
        public ApproveChallengeRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ApproveChallengeRequest class.
        /// </summary>
        /// <param name="challenge">Possible values include: 'Unknown', 'Sms',
        /// 'Email', 'Selfie', 'Words', 'Device', 'Pin', 'None'</param>
        public ApproveChallengeRequest(Challenge challenge, string recoveryId = default(string), string agentId = default(string))
        {
            RecoveryId = recoveryId;
            Challenge = challenge;
            AgentId = agentId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recoveryId")]
        public string RecoveryId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Sms', 'Email',
        /// 'Selfie', 'Words', 'Device', 'Pin', 'None'
        /// </summary>
        [JsonProperty(PropertyName = "challenge")]
        public Challenge Challenge { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "agentId")]
        public string AgentId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
