// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NewRecoveryRequest
    {
        /// <summary>
        /// Initializes a new instance of the NewRecoveryRequest class.
        /// </summary>
        public NewRecoveryRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NewRecoveryRequest class.
        /// </summary>
        public NewRecoveryRequest(string clientId = default(string))
        {
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ClientId != null)
            {
                if (ClientId.Length < 8)
                {
                    throw new ValidationException(ValidationRules.MinLength, "ClientId", 8);
                }
            }
        }
    }
}
