// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PasswordRequest
    {
        /// <summary>
        /// Initializes a new instance of the PasswordRequest class.
        /// </summary>
        public PasswordRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PasswordRequest class.
        /// </summary>
        public PasswordRequest(string recoveryId = default(string), string passwordHash = default(string))
        {
            RecoveryId = recoveryId;
            PasswordHash = passwordHash;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recoveryId")]
        public string RecoveryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "passwordHash")]
        public string PasswordHash { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RecoveryId != null)
            {
                if (RecoveryId.Length < 8)
                {
                    throw new ValidationException(ValidationRules.MinLength, "RecoveryId", 8);
                }
            }
        }
    }
}
