// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RecoveryStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the RecoveryStatusResponse class.
        /// </summary>
        public RecoveryStatusResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecoveryStatusResponse class.
        /// </summary>
        /// <param name="challenge">Possible values include: 'Unknown', 'Sms',
        /// 'Email', 'Selfie', 'Words', 'Device', 'Pin', 'None'</param>
        /// <param name="overallProgress">Possible values include: 'Ongoing',
        /// 'WaitingForSupport', 'Frozen', 'Suspended', 'Allowed'</param>
        public RecoveryStatusResponse(Challenge challenge, Progress overallProgress)
        {
            Challenge = challenge;
            OverallProgress = overallProgress;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets possible values include: 'Unknown', 'Sms', 'Email', 'Selfie',
        /// 'Words', 'Device', 'Pin', 'None'
        /// </summary>
        [JsonProperty(PropertyName = "challenge")]
        public Challenge Challenge { get; private set; }

        /// <summary>
        /// Gets possible values include: 'Ongoing', 'WaitingForSupport',
        /// 'Frozen', 'Suspended', 'Allowed'
        /// </summary>
        [JsonProperty(PropertyName = "overallProgress")]
        public Progress OverallProgress { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
