// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ClientAccountRecovery.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RecoveryTraceResponse
    {
        /// <summary>
        /// Initializes a new instance of the RecoveryTraceResponse class.
        /// </summary>
        public RecoveryTraceResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RecoveryTraceResponse class.
        /// </summary>
        /// <param name="previousState">Possible values include:
        /// 'RecoveryStarted', 'AwaitSecretPhrases', 'AwaitDeviceVerification',
        /// 'AwaitSmsVerification', 'AwaitEmailVerification',
        /// 'AwaitKycVerification', 'KycInProgress', 'AwaitPinCode',
        /// 'PasswordChangeFrozen', 'PasswordChangeSuspended', 'CallSupport',
        /// 'Transfer', 'PasswordChangeAllowed', 'PasswordChangeForbidden',
        /// 'PasswordUpdated'</param>
        /// <param name="action">Possible values include: 'RecoveryRequest',
        /// 'SecretPhrasesComplete', 'SecretPhrasesSkip',
        /// 'DeviceVerificationComplete', 'DeviceVerificationSkip',
        /// 'SmsVerificationComplete', 'SmsVerificationRestart',
        /// 'SmsVerificationFail', 'SmsVerificationSkip',
        /// 'EmailVerificationComplete', 'EmailVerificationRestart',
        /// 'EmailVerificationFail', 'EmailVerificationSkip', 'PinComplete',
        /// 'PinSkip', 'SelfieVerificationRequest',
        /// 'SelfieVerificationComplete', 'SelfieVerificationSkip',
        /// 'SelfieVerificationFail', 'JumpToSuspended', 'JumpToCallSupport',
        /// 'JumpToFrozen', 'JumpToAllowed', 'UpdatePassword'</param>
        /// <param name="newState">Possible values include: 'RecoveryStarted',
        /// 'AwaitSecretPhrases', 'AwaitDeviceVerification',
        /// 'AwaitSmsVerification', 'AwaitEmailVerification',
        /// 'AwaitKycVerification', 'KycInProgress', 'AwaitPinCode',
        /// 'PasswordChangeFrozen', 'PasswordChangeSuspended', 'CallSupport',
        /// 'Transfer', 'PasswordChangeAllowed', 'PasswordChangeForbidden',
        /// 'PasswordUpdated'</param>
        public RecoveryTraceResponse(System.DateTime time, State previousState, Trigger action, State newState, string initiator, string comment)
        {
            Time = time;
            PreviousState = previousState;
            Action = action;
            NewState = newState;
            Initiator = initiator;
            Comment = comment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public System.DateTime Time { get; private set; }

        /// <summary>
        /// Gets possible values include: 'RecoveryStarted',
        /// 'AwaitSecretPhrases', 'AwaitDeviceVerification',
        /// 'AwaitSmsVerification', 'AwaitEmailVerification',
        /// 'AwaitKycVerification', 'KycInProgress', 'AwaitPinCode',
        /// 'PasswordChangeFrozen', 'PasswordChangeSuspended', 'CallSupport',
        /// 'Transfer', 'PasswordChangeAllowed', 'PasswordChangeForbidden',
        /// 'PasswordUpdated'
        /// </summary>
        [JsonProperty(PropertyName = "previousState")]
        public State PreviousState { get; private set; }

        /// <summary>
        /// Gets possible values include: 'RecoveryRequest',
        /// 'SecretPhrasesComplete', 'SecretPhrasesSkip',
        /// 'DeviceVerificationComplete', 'DeviceVerificationSkip',
        /// 'SmsVerificationComplete', 'SmsVerificationRestart',
        /// 'SmsVerificationFail', 'SmsVerificationSkip',
        /// 'EmailVerificationComplete', 'EmailVerificationRestart',
        /// 'EmailVerificationFail', 'EmailVerificationSkip', 'PinComplete',
        /// 'PinSkip', 'SelfieVerificationRequest',
        /// 'SelfieVerificationComplete', 'SelfieVerificationSkip',
        /// 'SelfieVerificationFail', 'JumpToSuspended', 'JumpToCallSupport',
        /// 'JumpToFrozen', 'JumpToAllowed', 'UpdatePassword'
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public Trigger Action { get; private set; }

        /// <summary>
        /// Gets possible values include: 'RecoveryStarted',
        /// 'AwaitSecretPhrases', 'AwaitDeviceVerification',
        /// 'AwaitSmsVerification', 'AwaitEmailVerification',
        /// 'AwaitKycVerification', 'KycInProgress', 'AwaitPinCode',
        /// 'PasswordChangeFrozen', 'PasswordChangeSuspended', 'CallSupport',
        /// 'Transfer', 'PasswordChangeAllowed', 'PasswordChangeForbidden',
        /// 'PasswordUpdated'
        /// </summary>
        [JsonProperty(PropertyName = "newState")]
        public State NewState { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "initiator")]
        public string Initiator { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "comment")]
        public string Comment { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
